name: Build and change image

on:
  workflow_call:
    inputs:
      image_repository_name:
        required: true
        type: string
      timeout:
        type: string
        default: "5m"
      runner:
        required: true
        type: string
      dockerfile:
        type: string
        default: "Dockerfile"
      prefix:
        type: string
        default: ""
      environment:
        type: string
        default: "dev"
      directory:
        type: string
        default: "."
      region:
        type: string
        default: "us-west-2"
      role:
          required: true
          type: string
    # secrets:
    #   ROLE_TO_ASSUME:
    #     required: true

jobs:
  build:
    runs-on: ${{inputs.runner}}
    environment: ${{inputs.environment}}
    steps:
    - name: Clone
      uses: actions/checkout@v3

    - name: set job env
      run: |
        echo "TAG=${GITHUB_REF_NAME////_}" >> $GITHUB_ENV
        echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c 1-8`" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ${{ inputs.region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ${{ inputs.region }}

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker image build \
        --tag ${{ env.ECR_REGISTRY }}/${{inputs.image_repository_name}}:latest-${{inputs.prefix}} \
        --tag ${{ env.ECR_REGISTRY }}/${{inputs.image_repository_name}}:${TAG}-${{inputs.prefix}}-${SHORT_SHA} \
        -f ${{inputs.dockerfile}} \
        ${{ inputs.directory }}
        docker push ${{ env.ECR_REGISTRY }}/${{inputs.image_repository_name}}:latest-${{inputs.prefix}}
        docker push ${{ env.ECR_REGISTRY }}/${{inputs.image_repository_name}}:${TAG}-${{inputs.prefix}}-${SHORT_SHA}
